global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - 10.10.10.30:9090
        labels:
          role: monitoring
          node: monitor01

  - job_name: node
    static_configs:
      - targets:
          - 10.10.10.11:9100
          - 10.10.10.12:9100
          - 10.10.10.13:9100
        labels:
          role: proxmox
      - targets:
          - 10.10.10.30:9100
        labels:
          role: monitoring
      - targets:
          - 10.10.50.10:9100
        labels:
          role: bastion
      - targets:
          - 10.10.80.20:9100
        labels:
          role: htcondor-manager
      - targets:
          - 10.10.80.101:9100
          - 10.10.80.102:9100
          - 10.10.80.103:9100
          - 10.10.80.104:9100
        labels:
          role: htcondor-execute
