# Generated by Django 5.2.17 on 2026-09-11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("authentication", "Authentication"),
                            ("project", "Project"),
                            ("request", "Request"),
                            ("operation", "Operation"),
                            ("system", "System"),
                        ],
                        max_length=32,
                    ),
                ),
                ("action", models.CharField(max_length=64)),
                ("actor_label", models.CharField(blank=True, max_length=150)),
                (
                    "authentication_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("local", "Local account"),
                            ("oidc", "OpenID Connect"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                ("request_id", models.UUIDField(blank=True, null=True)),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("target_type", models.CharField(blank=True, max_length=64)),
                ("target_id", models.CharField(blank=True, max_length=128)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "action", "created_at"],
                        name="audit_category_action_time_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="audit_actor_time_idx",
                    ),
                    models.Index(
                        fields=["request_id"],
                        name="audit_request_id_idx",
                    ),
                ],
            },
        ),
    ]
