[Unit]
After=tailscaled.service network-online.target nginx.service npd-bastion-ssh-forward.service
Wants=network-online.target
Requires=tailscaled.service nginx.service npd-bastion-ssh-forward.service

[Service]
Restart=on-failure
RestartSec=10
StartLimitIntervalSec=180
StartLimitBurst=12
ExecStartPre=
ExecStartPre=/bin/sh -c 'for i in $(seq 1 30); do /usr/bin/tailscale status --peers=false >/dev/null 2>&1 && exit 0; sleep 2; done; /usr/bin/tailscale status --peers=false'
