# Generated by Django 5.2.17 on 2026-09-10 15:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('oidc_issuer', models.URLField(max_length=512)),
                ('oidc_subject', models.CharField(max_length=255)),
                ('cluster_login', models.CharField(blank=True, max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Use a lowercase Linux login, for example: denis', regex='^[a-z_][a-z0-9_-]{0,31}$')])),
                ('cluster_uid', models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(20000), django.core.validators.MaxValueValidator(29999)])),
                ('provisioning_status', models.CharField(choices=[('not_requested', 'Not requested'), ('pending', 'Pending'), ('active', 'Active'), ('failed', 'Failed'), ('disabled', 'Disabled')], default='not_requested', max_length=20)),
                ('provisioned_at', models.DateTimeField(blank=True, null=True)),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('oidc_issuer', 'oidc_subject'), name='accounts_profile_unique_oidc_identity'), models.CheckConstraint(condition=models.Q(('cluster_uid__isnull', True), models.Q(('cluster_uid__gte', 20000), ('cluster_uid__lte', 29999)), _connector='OR'), name='accounts_profile_cluster_uid_range'), models.CheckConstraint(condition=models.Q(models.Q(('cluster_login__isnull', True), ('cluster_uid__isnull', True)), models.Q(('cluster_login__isnull', False), ('cluster_uid__isnull', False)), _connector='OR'), name='accounts_profile_cluster_identity_pair')],
            },
        ),
    ]
