all:
  children:
    alma_basic:
      hosts:
        asus-r1n1.internal:
          ansible_host: 10.10.80.101
        asus-r1n2.internal:
          ansible_host: 10.10.80.102
        asus-r1n3.internal:
          ansible_host: 10.10.80.103
        asus-r1n4.internal:
          ansible_host: 10.10.80.104
    asus_nodes:
      hosts:
        asus-r1n1.internal:
          ansible_host: 10.10.80.101
        asus-r1n2.internal:
          ansible_host: 10.10.80.102
        asus-r1n3.internal:
          ansible_host: 10.10.80.103
        asus-r1n4.internal:
          ansible_host: 10.10.80.104
    supermicro_execute_vms:
      hosts: {}
  vars:
    ansible_user: npdadmin
    ansible_become: true
