all:
  children:
    alma_basic:
      hosts: {}
    asus_nodes:
      hosts:
        # asus-r1n1.internal:
        #   ansible_host: 10.10.80.x
    supermicro_execute_vms:
      hosts: {}
  vars:
    ansible_user: npdadmin
    ansible_become: true
