"""link virtual machines to ssh public keys

Revision ID: 2941d636dcb4
Revises: 7cd984e1f600
Create Date: 2026-09-23 18:56:01.390362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2941d636dcb4'
down_revision: Union[str, Sequence[str], None] = '7cd984e1f600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_machines', sa.Column('ssh_public_key_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_virtual_machines_ssh_public_key_id'), 'virtual_machines', ['ssh_public_key_id'], unique=False)
    op.create_foreign_key(
    "virtual_machines_ssh_public_key_id_fkey",
    "virtual_machines",
    "ssh_public_keys",
    ["ssh_public_key_id"],
    ["id"],
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
    "virtual_machines_ssh_public_key_id_fkey",
    "virtual_machines",
    type_="foreignkey",
    )   
    op.drop_index(op.f('ix_virtual_machines_ssh_public_key_id'), table_name='virtual_machines')
    op.drop_column('virtual_machines', 'ssh_public_key_id')
    # ### end Alembic commands ###
