"""make ssh key fingerprint globally unique

Revision ID: 4f942b4ebb00
Revises: 2941d636dcb4
Create Date: 2026-09-23 19:02:58.533069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f942b4ebb00'
down_revision: Union[str, Sequence[str], None] = '2941d636dcb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_ssh_public_keys_owner_fingerprint'), 'ssh_public_keys', type_='unique')
    op.create_unique_constraint('uq_ssh_public_keys_fingerprint', 'ssh_public_keys', ['fingerprint'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ssh_public_keys_fingerprint', 'ssh_public_keys', type_='unique')
    op.create_unique_constraint(op.f('uq_ssh_public_keys_owner_fingerprint'), 'ssh_public_keys', ['owner_user_id', 'fingerprint'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
