"""add phase to operations

Revision ID: 4fa6b2ff7397
Revises: 4f942b4ebb00
Create Date: 2026-09-23 19:42:46.975330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fa6b2ff7397'
down_revision: Union[str, Sequence[str], None] = '4f942b4ebb00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('phase', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operations', 'phase')
    # ### end Alembic commands ###
