"""create ssh public keys table

Revision ID: 7cd984e1f600
Revises: d9fa31f08e64
Create Date: 2026-09-22 17:13:35.599150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd984e1f600'
down_revision: Union[str, Sequence[str], None] = 'd9fa31f08e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ssh_public_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('key_type', sa.String(length=50), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('fingerprint', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'fingerprint', name='uq_ssh_public_keys_owner_fingerprint'),
    sa.UniqueConstraint('owner_user_id', 'name', name='uq_ssh_public_keys_owner_name')
    )
    op.create_index(op.f('ix_ssh_public_keys_owner_user_id'), 'ssh_public_keys', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ssh_public_keys_owner_user_id'), table_name='ssh_public_keys')
    op.drop_table('ssh_public_keys')
    # ### end Alembic commands ###
