"""create compute plans table

Revision ID: 903299d0b202
Revises: 789d1f469a23
Create Date: 2026-09-16 14:59:23.340529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import UUID, String, Integer


# revision identifiers, used by Alembic.
revision: str = '903299d0b202'
down_revision: Union[str, Sequence[str], None] = '789d1f469a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compute_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('max_vms', sa.Integer(), nullable=False),
    sa.Column('max_running_vms', sa.Integer(), nullable=False),
    sa.Column('max_total_vcpus', sa.Integer(), nullable=False),
    sa.Column('max_total_memory_mb', sa.Integer(), nullable=False),
    sa.Column('max_total_storage_gb', sa.Integer(), nullable=False),
    sa.Column('max_shared_storage_gb', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_running_vms <= max_vms', name='ck_compute_plans_running_vms_limit'),
    sa.CheckConstraint('max_running_vms >= 0', name='ck_compute_plans_max_running_vms_non_negative'),
    sa.CheckConstraint('max_total_memory_mb >= 0', name='ck_compute_plans_memory_non_negative'),
    sa.CheckConstraint('max_total_storage_gb >= 0', name='ck_compute_plans_storage_non_negative'),
    sa.CheckConstraint('max_shared_storage_gb >= 0', name= 'ck_compute_plans_shared_storage_non_negative'),
    sa.CheckConstraint('max_total_vcpus >= 0', name='ck_compute_plans_vcpus_non_negative'),
    sa.CheckConstraint('max_vms >= 0', name='ck_compute_plans_max_vms_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_compute_plans_code')
    )
    
    compute_plans_table = sa.table(
    "compute_plans",
    sa.column("id", UUID),
    sa.column("code", String),
    sa.column("max_vms", Integer),
    sa.column("max_running_vms", Integer),
    sa.column("max_total_vcpus", Integer),
    sa.column("max_total_memory_mb", Integer),
    sa.column("max_total_storage_gb", Integer),
    sa.column("max_shared_storage_gb", Integer)
    )
    op.bulk_insert(
        compute_plans_table,
        [
            {
                "id": "bc62178c-1526-4070-bd8e-697754db8dbd",
                "code": "starter",
                "max_vms": 1,
                "max_running_vms": 1,
                "max_total_vcpus": 4,
                "max_total_memory_mb": 16384,
                "max_total_storage_gb": 100,
                "max_shared_storage_gb": 0
            },
        ]
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compute_plans')
    # ### end Alembic commands ###
