"""create virtual machines table

Revision ID: 960f9479ecad
Revises: 1b47a1f1aaff
Create Date: 2026-09-17 18:05:49.037833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960f9479ecad'
down_revision: Union[str, Sequence[str], None] = '1b47a1f1aaff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_machines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('requested_vcpus', sa.Integer(), nullable=False),
    sa.Column('requested_memory_mb', sa.Integer(), nullable=False),
    sa.Column('requested_storage_gb', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('provider_vmid', sa.Integer(), nullable=True),
    sa.Column('provider_node', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'pending_capacity', 'provisioning', 'running', 'stopped', 'failed', 'deleting', 'deleted')", name='vm_user_status'),
    sa.CheckConstraint('requested_memory_mb > 0', name='vm_requested_memory_mb_positive'),
    sa.CheckConstraint('requested_storage_gb > 0', name='vm_requested_storage_gb_positive'),
    sa.CheckConstraint('requested_vcpus > 0', name='vm_requested_vcpus_positive'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_vmid', name='vm_provider_vmid_unique')
    )
    op.create_index(op.f('ix_virtual_machines_owner_user_id'), 'virtual_machines', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_virtual_machines_owner_user_id'), table_name='virtual_machines')
    op.drop_table('virtual_machines')
    # ### end Alembic commands ###
