"""create operations table

Revision ID: bff9f843fb90
Revises: a2f3d8c68eb2
Create Date: 2026-09-18 11:07:27.590467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bff9f843fb90'
down_revision: Union[str, Sequence[str], None] = 'a2f3d8c68eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('virtual_machine_id', sa.Uuid(), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("operation_type IN ('vm.create', 'vm.start', 'vm.stop', 'vm.delete')", name='operation_type_list'),
    sa.CheckConstraint("status IN ('pending', 'processing', 'succeeded', 'failed')", name='operations_status_list'),
    sa.CheckConstraint('attempts >= 0', name='operations_attempts_not_negative'),
    sa.ForeignKeyConstraint(['virtual_machine_id'], ['virtual_machines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint("idempotency_key", name="uq_operations_idempotency_key")
    )
    op.create_index(op.f('ix_operations_status'), 'operations', ['status'], unique=False)
    op.create_index(op.f('ix_operations_virtual_machine_id'), 'operations', ['virtual_machine_id'], unique=False)
    # ### end Alembic commands ###

    op.execute(
    """
    INSERT INTO operations (
        id,
        virtual_machine_id,
        operation_type,
        status,
        idempotency_key,
        attempts
    )
    SELECT
        id,
        id,
        'vm.create',
        'pending',
        'backfill-vm-create:' || id::text,
        0
    FROM virtual_machines
    WHERE status = 'pending'
    """
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operations_virtual_machine_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_status'), table_name='operations')
    op.drop_table('operations')
    # ### end Alembic commands ###
