"""create user quotas table

Revision ID: d3c70f1c2755
Revises: 903299d0b202
Create Date: 2026-09-16 22:31:16.392613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3c70f1c2755'
down_revision: Union[str, Sequence[str], None] = '903299d0b202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_quota',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('compute_plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'suspended')", name='ck_user_status'),
    sa.ForeignKeyConstraint(['compute_plan_id'], ['compute_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_quota_compute_plan_id'), 'user_quota', ['compute_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_quota_compute_plan_id'), table_name='user_quota')
    op.drop_table('user_quota')
    # ### end Alembic commands ###
