"""add provider task id into table operations

Revision ID: d9fa31f08e64
Revises: bff9f843fb90
Create Date: 2026-09-20 22:45:09.803962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9fa31f08e64'
down_revision: Union[str, Sequence[str], None] = 'bff9f843fb90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('provider_task_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operations', 'provider_task_id')
    # ### end Alembic commands ###
